pulsar:
  client:
    serviceUrl: pulsar://localhost:6650
    tls:
      tlsAllowInsecureConnection: true
      tlsHostnameVerificationEnable: false
    auth:
      userName: <username>
      password: <password>
  topic:
    name: my-topic
    subscription:
      name: my-sub
      type: Key_Shared
    consumer:
      count: 1

server:
  port: 8081